# Generated by Django 5.0.4 on 2024-04-23 08:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('config', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_pic', models.ImageField(blank=True, null=True, upload_to='profile_pics/')),
                ('employee_id', models.CharField(max_length=20, unique=True)),
                ('employee_name', models.CharField(max_length=100)),
                ('device_enroll_id', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone_no', models.PositiveBigIntegerField(blank=True, null=True)),
                ('pf_no', models.CharField(blank=True, max_length=20, null=True)),
                ('esi_no', models.CharField(blank=True, max_length=20, null=True)),
                ('insurance_no', models.CharField(blank=True, max_length=20, null=True)),
                ('bank_name', models.CharField(blank=True, max_length=100, null=True)),
                ('bank_branch', models.CharField(blank=True, max_length=100, null=True)),
                ('bank_account_no', models.CharField(blank=True, max_length=20, null=True)),
                ('bank_account_name', models.CharField(blank=True, max_length=100, null=True)),
                ('bank_account_type', models.CharField(blank=True, choices=[('Savings Account', 'Savings Account'), ('Current Account', 'Current Account'), ('Salary Account', 'Salary Account'), ('NRI Account', 'NRI Account'), ('Pension Account', 'Pension Account'), ('Other Account', 'Other Account')], max_length=20, null=True)),
                ('ifsc_code', models.CharField(blank=True, max_length=20, null=True)),
                ('category', models.CharField(blank=True, choices=[('Permanent Employee', 'Permanent Employee'), ('Temporary Employee', 'Temporary Employee'), ('Contractor Employee', 'Contractor Employee')], max_length=100, null=True)),
                ('job_type', models.CharField(blank=True, choices=[('Training', 'Training'), ('Confirmed', 'Confirmed'), ('Professional', 'Professional')], max_length=100, null=True)),
                ('date_of_joining', models.DateField(blank=True, null=True)),
                ('date_of_leaving', models.DateField(blank=True, null=True)),
                ('job_status', models.CharField(blank=True, choices=[('Active', 'Active'), ('Resigned', 'Resigned'), ('Absconded', 'Absconded')], max_length=100, null=True)),
                ('reason_for_leaving', models.TextField(blank=True, null=True)),
                ('emergency_contact_name', models.CharField(blank=True, max_length=100, null=True)),
                ('emergency_contact_no', models.PositiveBigIntegerField(blank=True, null=True)),
                ('marital_status', models.CharField(blank=True, choices=[('Single', 'Single'), ('Married', 'Married'), ('Divorced', 'Divorced'), ('Widowed', 'Widowed')], max_length=20, null=True)),
                ('spouse_name', models.CharField(blank=True, max_length=100, null=True)),
                ('blood_group', models.CharField(blank=True, max_length=10, null=True)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('country_name', models.CharField(blank=True, max_length=100, null=True)),
                ('country_code', models.CharField(blank=True, max_length=10, null=True)),
                ('uid_no', models.CharField(blank=True, max_length=20, null=True)),
                ('pan_no', models.CharField(blank=True, max_length=20, null=True)),
                ('voter_id', models.CharField(blank=True, max_length=20, null=True)),
                ('driving_license', models.CharField(blank=True, max_length=20, null=True)),
                ('gender', models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=10, null=True)),
                ('present_address', models.TextField(blank=True, null=True)),
                ('permanent_address', models.TextField(blank=True, null=True)),
                ('additional_info', models.TextField(blank=True, null=True)),
                ('graduation', models.CharField(blank=True, max_length=100, null=True)),
                ('course_type', models.CharField(blank=True, choices=[('Under Graduate', 'Under Graduate'), ('Post Graduate', 'Post Graduate'), ('Diploma', 'Diploma'), ('Certificate', 'Certificate'), ('Other', 'Other')], max_length=100, null=True)),
                ('course', models.CharField(blank=True, max_length=100, null=True)),
                ('place_of_graduation', models.CharField(blank=True, max_length=100, null=True)),
                ('aggregate', models.FloatField(blank=True, null=True)),
                ('year_of_graduation', models.PositiveIntegerField(blank=True, null=True)),
                ('first_weekly_off', models.CharField(blank=True, choices=[('Sunday', 'Sunday'), ('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Saturday', 'Saturday')], max_length=20, null=True)),
                ('second_weekly_off', models.CharField(blank=True, choices=[('Sunday', 'Sunday'), ('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Saturday', 'Saturday')], max_length=20, null=True)),
                ('week_off_effective_date', models.DateField(blank=True, null=True)),
                ('flexi_time', models.BooleanField(default=False)),
                ('consider_late_entry', models.BooleanField(default=False)),
                ('consider_early_exit', models.BooleanField(default=False)),
                ('consider_extra_hours_worked', models.BooleanField(default=False)),
                ('consider_late_entry_on_holiday', models.BooleanField(default=False)),
                ('consider_early_exit_on_holiday', models.BooleanField(default=False)),
                ('consider_extra_hours_worked_on_holiday', models.BooleanField(default=False)),
                ('search_next_day', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('alt_reporting_manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alt_reports', to='resource.employee')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='config.company')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='config.department')),
                ('designation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='config.designation')),
                ('division', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='config.division')),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='config.location')),
                ('reporting_manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports', to='resource.employee')),
                ('shopfloor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='config.shopfloor')),
                ('subdivision', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='config.subdivision')),
            ],
            options={
                'verbose_name': 'Employee',
                'verbose_name_plural': 'Employees',
                'db_table': 'employee',
                'ordering': ['id'],
            },
        ),
    ]
