# Generated by Django 5.0.4 on 2024-04-29 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0001_initial'),
        ('resource', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='logs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idno', models.IntegerField(blank=True, null=True)),
                ('employeeid', models.IntegerField(blank=True, null=True)),
                ('logdate', models.DateField(blank=True, null=True)),
                ('logtime', models.TimeField(blank=True, null=True)),
                ('direction', models.CharField(blank=True, max_length=50, null=True)),
                ('shortname', models.CharField(blank=True, max_length=50, null=True)),
                ('serialno', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='employee',
            name='profile_pic',
            field=models.ImageField(blank=True, default='default_pic.jpg', null=True, upload_to='profile_pics/'),
        ),
        migrations.AddIndex(
            model_name='employee',
            index=models.Index(fields=['id'], name='employee_id_f33e0d_idx'),
        ),
        migrations.AddIndex(
            model_name='employee',
            index=models.Index(fields=['employee_id', 'employee_name', 'email', 'phone_no', 'pf_no', 'esi_no', 'insurance_no', 'bank_name', 'bank_branch', 'bank_account_no', 'bank_account_name', 'bank_account_type', 'ifsc_code', 'category', 'job_type', 'job_status', 'emergency_contact_name', 'emergency_contact_no', 'marital_status', 'spouse_name', 'blood_group', 'date_of_birth', 'country_name', 'country_code', 'uid_no', 'pan_no', 'voter_id', 'driving_license'], name='employee_employe_e43f48_idx'),
        ),
    ]
