# Generated by Django 5.0.4 on 2024-04-29 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resource', '0002_logs_alter_employee_profile_pic_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='logs',
            index=models.Index(fields=['idno', 'employeeid', 'logdate', 'logtime', 'direction', 'shortname', 'serialno'], name='logs_idno_e2aca0_idx'),
        ),
        migrations.AlterModelTable(
            name='logs',
            table='logs',
        ),
    ]
