# Generated by Django 5.0.4 on 2024-04-30 08:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resource', '0004_attendance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendance',
            name='category',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='company',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='department',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='designation',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='device_enroll_id',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='employee_name',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='job_type',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='location',
        ),
        migrations.AlterField(
            model_name='attendance',
            name='employeeid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='resource.employee'),
        ),
    ]
