# Generated by Django 5.0.4 on 2024-05-10 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resource', '0006_alter_attendance_unique_together_employee_shift'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='early_exit',
            field=models.TimeField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='late_entry',
            field=models.TimeField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='overtime',
            field=models.TimeField(blank=True, default=None, null=True),
        ),
    ]
