# Generated by Django 5.0.4 on 2024-05-14 02:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resource', '0007_alter_attendance_early_exit_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendance',
            name='date_of_joining',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='date_of_leaving',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='shift',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='status',
        ),
    ]
