# Generated by Django 5.0.4 on 2024-05-21 06:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0002_shift'),
        ('resource', '0008_remove_attendance_date_of_joining_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='shift',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='config.shift'),
        ),
    ]
